"""permissoes do app, dispositivos de push e trava de avisos

Revision ID: 2f7a0b2f92b4
Revises: d4a80f1c9e27
Create Date: 2026-08-15 19:03:23.421625
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f7a0b2f92b4'
down_revision: Union[str, None] = 'd4a80f1c9e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gs_avisos_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=120), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chave', name='uq_gs_aviso_enviado')
    )
    op.create_index(op.f('ix_gs_avisos_enviados_chave'), 'gs_avisos_enviados', ['chave'], unique=False)
    op.create_index(op.f('ix_gs_avisos_enviados_user_id'), 'gs_avisos_enviados', ['user_id'], unique=False)
    op.create_table('gs_push_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('plataforma', sa.String(length=16), nullable=True),
    sa.Column('versao_app', sa.String(length=32), nullable=True),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visto_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gs_push_devices_token'), 'gs_push_devices', ['token'], unique=True)
    op.create_index(op.f('ix_gs_push_devices_user_id'), 'gs_push_devices', ['user_id'], unique=False)
    op.create_table('gs_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('subcategoria', sa.String(length=60), nullable=False),
    sa.Column('concedida_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('concedida_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concedida_por'], ['gs_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'categoria', 'subcategoria', name='uq_gs_permissao')
    )
    op.create_index(op.f('ix_gs_user_permissions_categoria'), 'gs_user_permissions', ['categoria'], unique=False)
    op.create_index(op.f('ix_gs_user_permissions_user_id'), 'gs_user_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gs_user_permissions_user_id'), table_name='gs_user_permissions')
    op.drop_index(op.f('ix_gs_user_permissions_categoria'), table_name='gs_user_permissions')
    op.drop_table('gs_user_permissions')
    op.drop_index(op.f('ix_gs_push_devices_user_id'), table_name='gs_push_devices')
    op.drop_index(op.f('ix_gs_push_devices_token'), table_name='gs_push_devices')
    op.drop_table('gs_push_devices')
    op.drop_index(op.f('ix_gs_avisos_enviados_user_id'), table_name='gs_avisos_enviados')
    op.drop_index(op.f('ix_gs_avisos_enviados_chave'), table_name='gs_avisos_enviados')
    op.drop_table('gs_avisos_enviados')
    # ### end Alembic commands ###
