"""clientes: perfis, vinculos de produto e senha provisoria

Revision ID: 7f19c7de9682
Revises: c35f904f4e86
Create Date: 2026-08-12 14:31:35.693386
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f19c7de9682'
down_revision: Union[str, None] = 'c35f904f4e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gs_senhas_provisorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gs_user_id', sa.Integer(), nullable=False),
    sa.Column('gerada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('gerada_por', sa.Integer(), nullable=True),
    sa.Column('usada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gerada_por'], ['gs_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gs_user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gs_senhas_provisorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_senhas_provisorias_gs_user_id'), ['gs_user_id'], unique=False)

    op.create_table('gs_vinculos_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gs_user_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=20), nullable=False),
    sa.Column('usuario_remoto_id', sa.String(length=64), nullable=False),
    sa.Column('usuario_remoto_email', sa.String(length=255), nullable=True),
    sa.Column('usuario_remoto_nome', sa.String(length=255), nullable=True),
    sa.Column('vinculado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('vinculado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gs_user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vinculado_por'], ['gs_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gs_user_id', 'produto', name='uq_usuario_produto')
    )
    with op.batch_alter_table('gs_vinculos_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_vinculos_produto_gs_user_id'), ['gs_user_id'], unique=False)

    with op.batch_alter_table('gs_user_plant_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concedido_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('revalidado_em')

    with op.batch_alter_table('gs_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.Enum('CLIENTE', 'ATENDIMENTO', 'ADMINISTRADOR', name='perfil', native_enum=False, length=20), nullable=False))
        batch_op.add_column(sa.Column('trocar_senha', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_index(batch_op.f('ix_gs_users_mp_user_id'))
        batch_op.drop_index(batch_op.f('ix_gs_users_mw_user_id'))
        batch_op.drop_column('is_gestor')
        batch_op.drop_column('mp_user_id')
        batch_op.drop_column('mw_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gs_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mw_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mp_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_gestor', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_gs_users_mw_user_id'), ['mw_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gs_users_mp_user_id'), ['mp_user_id'], unique=False)
        batch_op.drop_column('trocar_senha')
        batch_op.drop_column('perfil')

    with op.batch_alter_table('gs_user_plant_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revalidado_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('concedido_em')

    with op.batch_alter_table('gs_vinculos_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_vinculos_produto_gs_user_id'))

    op.drop_table('gs_vinculos_produto')
    with op.batch_alter_table('gs_senhas_provisorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_senhas_provisorias_gs_user_id'))

    op.drop_table('gs_senhas_provisorias')
    # ### end Alembic commands ###
