"""painel do gestor: integracoes, senha e cargo

Revision ID: c35f904f4e86
Revises: 
Create Date: 2026-08-12 13:11:20.122014
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c35f904f4e86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gs_integracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.Enum('MEUWATT', 'MEUPLANO', name='produto', native_enum=False, length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('usuario_servico', sa.String(length=255), nullable=False),
    sa.Column('senha_cifrada', sa.Text(), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('estado', sa.Enum('NUNCA', 'OK', 'FALHOU', name='estadoteste', native_enum=False, length=20), nullable=False),
    sa.Column('testada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detalhe_teste', sa.Text(), nullable=True),
    sa.Column('usinas_visiveis', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto')
    )
    op.create_table('gs_plant_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_plant_slug', sa.String(length=120), nullable=True),
    sa.Column('mp_usina_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('kwp', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gs_plant_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_plant_links_mp_usina_id'), ['mp_usina_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gs_plant_links_mw_plant_slug'), ['mw_plant_slug'], unique=False)

    op.create_table('gs_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('mw_user_id', sa.Integer(), nullable=True),
    sa.Column('mp_user_id', sa.Integer(), nullable=True),
    sa.Column('nivel_acesso', sa.Integer(), server_default='0', nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('is_gestor', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gs_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_gs_users_mp_user_id'), ['mp_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gs_users_mw_user_id'), ['mw_user_id'], unique=False)

    op.create_table('gs_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.Enum('MEUWATT', 'MEUPLANO', name='produto', native_enum=False, length=20), nullable=False),
    sa.Column('valor_mensal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gs_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('gs_user_plant_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_link_id', sa.Integer(), nullable=False),
    sa.Column('revalidado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_link_id'], ['gs_plant_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gs_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plant_link_id', name='uq_user_plant')
    )
    with op.batch_alter_table('gs_user_plant_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_user_plant_access_user_id'), ['user_id'], unique=False)

    op.create_table('gs_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['gs_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'competencia', name='uq_assinatura_competencia')
    )
    with op.batch_alter_table('gs_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gs_invoices_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gs_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_invoices_subscription_id'))

    op.drop_table('gs_invoices')
    with op.batch_alter_table('gs_user_plant_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_user_plant_access_user_id'))

    op.drop_table('gs_user_plant_access')
    with op.batch_alter_table('gs_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_subscriptions_user_id'))

    op.drop_table('gs_subscriptions')
    with op.batch_alter_table('gs_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_users_mw_user_id'))
        batch_op.drop_index(batch_op.f('ix_gs_users_mp_user_id'))
        batch_op.drop_index(batch_op.f('ix_gs_users_email'))

    op.drop_table('gs_users')
    with op.batch_alter_table('gs_plant_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gs_plant_links_mw_plant_slug'))
        batch_op.drop_index(batch_op.f('ix_gs_plant_links_mp_usina_id'))

    op.drop_table('gs_plant_links')
    op.drop_table('gs_integracoes')
    # ### end Alembic commands ###
